<a href="https://colab.research.google.com/github/Akifhossain29/ML-lab/blob/main/prac_lab_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
b=np.array([
    [1,2],
    [3,4],
    [5,6]
])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a.shape,b.shape

((4,), (3, 2))

In [ ]:
c = np.zeros((3,4),dtype=int)
c

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
d=np.ones((3,4),dtype=int)*9
d

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [ ]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [ ]:
c.shape,c.ndim,c.dtype

((3, 4), 2, dtype('int64'))

In [ ]:
sevens=np.ones((3,3),dtype=int)*7
sevens

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
r_shape=np.arange(1,13)
print(r_shape)
r_shape.reshape((3,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
x = np.array([10,20,30,40,50])
x, int(x[0]), int(x[-2])

(array([10, 20, 30, 40, 50]), 10, 40)

In [ ]:
# x[begin:end]
x [2:]

array([30, 40, 50])

In [ ]:
x = np.array([[1,2,3,55,56,57],
             [4,5,6,66,67,68],
             [7,8,9,99,96,97],
             [33,44,50,23,45,23]])
x

array([[ 1,  2,  3, 55, 56, 57],
       [ 4,  5,  6, 66, 67, 68],
       [ 7,  8,  9, 99, 96, 97],
       [33, 44, 50, 23, 45, 23]])

In [ ]:
int(x[1,1]),int(x[1,2])

(5, 6)

In [ ]:
x[1:2,1:3]

array([[5, 6]])

In [ ]:
x[2:,4:]

array([[96, 97],
       [45, 23]])

In [ ]:
v = np.array([0.2,1.5,-0.7,3.3,2.2])
v

array([ 0.2,  1.5, -0.7,  3.3,  2.2])

In [ ]:
mask=v>1.0
mask

array([False,  True, False,  True,  True])

In [ ]:
v[mask==False]

array([ 0.2, -0.7])

In [ ]:
v[mask==True]

array([1.5, 3.3, 2.2])

In [ ]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
x+y

array([11, 22, 33])

In [ ]:
x*y

array([10, 40, 90])

In [ ]:
X = np.random.randint(0, 10, size=(4, 3))
print(X)
# Global sum: reduces everything to a single number
print("Global sum:", X.sum())
# axis=0: reduce over rows -> gives one value per column (per feature)
print("Sum per feature (axis=0):", X.sum(axis=0))
# axis=1: reduce over columns -> gives one value per row (per sample)
print("Sum per sample (axis=1):", X.sum(axis=1))

[[6 9 8]
 [6 8 7]
 [1 0 6]
 [6 7 4]]
Global sum: 68
Sum per feature (axis=0): [19 24 25]
Sum per sample (axis=1): [23 21  7 17]


In [ ]:
#Mean, std, min, max (common in preprocessing)
# Feature-wise mean (1 value per feature)
mu = X.mean(axis=0)
print("Mean per feature:", mu)
# Feature-wise std (1 value per feature)
sigma = X.std(axis=0)
print("Std per feature:", sigma)
# Feature-wise min/max
print("Min per feature:", X.min(axis=0))
print("Max per feature:", X.max(axis=0))

Mean per feature: [4.75 6.   6.25]
Std per feature: [2.16506351 3.53553391 1.47901995]
Min per feature: [1 0 4]
Max per feature: [6 9 8]


In [ ]:
A=np.ones((3,2))
B=np.zeros((3,2))
C1=np.concatenate([A,B],axis=1)
print("Feature concat (axis=1):\n", C1)
print("Shape:", C1.shape)
C_samp = np.concatenate([A, B], axis=0)
print("Sample concat (axis=0):\n", C_samp)
print("vstack\n", np.vstack([A, B]))
print("hstack\n", np.hstack([A, B]))


Feature concat (axis=1):
 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]
Shape: (3, 4)
Sample concat (axis=0):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
vstack
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
hstack
 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]
